version: '3.7'

services:
  main:
    image: kartoza/postgis:13-3.1
    environment:
      - DEFAULT_ENCODING="UTF8"
      - DEFAULT_COLLATION="en_US.UTF-8"
      - DEFAULT_CTYPE="en_US.UTF-8"
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DBNAME=loop
      - ALLOW_IP_RANGE=0.0.0.0/0
      - REPLICATION=true
      - REPLICATION_USER=replicator
      - REPLICATION_PASS=replicatorpw
      - WAL_LEVEL=replica
    ports:
      - 5432:5432
    volumes:
      - loop-main-data:/var/lib/postgresql
  replica:
    image: kartoza/postgis:13-3.1
    environment:
      - DEFAULT_ENCODING="UTF8"
      - DEFAULT_COLLATION="en_US.UTF-8"
      - DEFAULT_CTYPE="en_US.UTF-8"
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DBNAME=loop
      - ALLOW_IP_RANGE=0.0.0.0/0
      - REPLICATION=true
      - REPLICATE_FROM=main
      - REPLICATION_USER=replicator
      - REPLICATION_PASS=replicatorpw
    ports:
      - 5433:5432
    depends_on:
      - main
    volumes:
      - loop-replica-data:/var/lib/postgresql

volumes:
  loop-main-data:
  loop-replica-data:
